PHP_IMAGE := "php-composer-__Php__:local"

@help:
    echo "Usage:"
    echo "  just build        - Builds the necessary Docker images."
    echo "  just install      - Installs project dependencies."
    echo "  just test         - Runs the test suite."
    echo "  just coverage     - Generates a coverage report using PCOV."
    echo "  just clean        - Removes the Docker images."
    echo "  just help         - Displays this help message."

build:
    docker build -t {{ PHP_IMAGE }} -f docker/php/Dockerfile .

install:
    docker run --rm -v "$(pwd):/var/www/html" {{ PHP_IMAGE }} composer install

test:
    docker run --rm -v "$(pwd):/var/www/html" {{ PHP_IMAGE }} composer test

coverage:
    docker run --rm -v "$(pwd):/var/www/html" {{ PHP_IMAGE }} composer coverage

clean:
    docker rmi {{ PHP_IMAGE }} || true
